apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommend-tag
  template:
    metadata:
      labels:
        app: recommend-tag
    spec:
      containers:
      - name: recommend-container
        image: 825958448855.dkr.ecr.ap-northeast-2.amazonaws.com/translate_test:4
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: recommend-service
spec:
  type: NodePort
  selector:
    app: recommend-tag
  ports:
    - nodePort: 31000
      port: 8080
      targetPort: 8080
